version: '3.8'

services:
  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "maria-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "proxy"
      DB_MYSQL_NAME: "proxy"
      DB_MYSQL_PASSWORD__FILE: /run/secrets/MYSQL_PWD
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - data:/data
      - etc-letsencrypt:/etc/letsencrypt
    secrets:
      - MYSQL_PWD
    networks:
      - home-network

  maria-db:
    image: 'mariadb:latest'
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PWD
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PWD
      MYSQL_DATABASE: 'proxy'
      MYSQL_USER: 'proxy'
    volumes:
      - var-lib-mysql:/var/lib/mysql
    secrets:
      - MYSQL_ROOT_PWD
      - MYSQL_PWD
    networks:
      - home-network

  adminer:
    image: adminer
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8080

networks:
  home-network:


volumes:
  data:
  etc-letsencrypt:
  var-lib-mysql:


secrets:
  # Secrets are single-line text files where the sole content is the secret
  # Paths in this example assume that secrets are kept in local folder called ".secrets"
  MYSQL_ROOT_PWD:
    external: true
  MYSQL_PWD:
    external: true
