version: '3.8'

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v2.4.2 # 
    ports:
        - "9925:9000" # 
    deploy:
      resources:
        limits:
          memory: 1000M # 
    volumes:
      - mealie-data:/app/data/
    environment:
      # Set Backend ENV Variables Here
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: Europe/Berlin
      BASE_URL: https://mealie.home.local
      # Database Settings
      DB_ENGINE: postgres
      POSTGRES_USER: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie
      # Default
      DEFAULT_GROUP: Home
      DEFAULT_HOUSEHOLD: Home
    secrets:
      - POSTGRES_PASSWORD
      - DEFAULT_MAIL
      - SMTP_HOST
      - SMTP_MAIL
      - SMTP_USER
      - SMTP_PASSWORD

  postgres:
    image: postgres:15
    volumes:
      - mealie-pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: run/secrets/POSTGRES_PASSWORD
      POSTGRES_USER: mealie
      PGUSER: mealie
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    secrets:
      - POSTGRES_PASSWORD

volumes:
  mealie-data:
  mealie-pgdata:
  
secrets:
    POSTGRES_PASSWORD:
        external: true
    DEFAULT_MAIL:
        external: true
    SMTP_HOST:
        external: true
    SMTP_MAIL:
        external: true
    SMTP_USER:
        external: true
    SMTP_PASSWORD:
        external: true
        
networks:
  default:
    external: true
    name: home-network